Fixes #1.

diff --git a/scripts/setup-tpch-db b/scripts/setup-tpch-db
--- a/scripts/setup-tpch-db
+++ b/scripts/setup-tpch-db
@@ -6,7 +6,7 @@
 # and generated data set (with user-specified scale factor). Must be run
 # after MonetDB itself has been properly installed and is available in the
 # executable search path
-# 
+#
 #################################################################################
 # By Eyal Rozenberg <eyalroz@technion.ac.il>
 ##################################################################################
@@ -20,7 +20,7 @@ function usage {
 	echo "Usage: $0 [OPTIONS...]"
 	echo "Downloads, build and installs MonetDB and the dbgen utlilities; generates TPC-H"
 	echo "data, creates a DB farm, creates a DB and loads the data there."
-	echo 
+	echo
 	echo "Options:"
 	echo "  -r, --recreate              If the TPC-H database exists, recreate it, dropping"
 	echo "                              all existing data. (If this option is unset, the "
@@ -29,27 +29,28 @@ function usage {
 	echo "  -G, --use-generated         Use previously-generated table load files (in the"
 	echo "                              data generation directory instead of re-generating"
 	echo "                              them using the dbgen utility."
-	echo "  -g, --dbgen-dir             Look for the TPC-H data generation utility in the"
-	echo "                              specified directory."
 	echo "  -l, --log-file FILENAME     Name of the file to log output into"
 	echo "  -d, --db-name NAME          Name of the database holding TPC-H test data"
-	echo "                              within the DB farm" 
+	echo "                              within the DB farm"
 	echo "  -f, --db-farm PATH          Filesystem path for the root directory of the DB farm"
 	echo "                              with the generated DB"
-	echo "  -p, --port NUMBER           Network port on the local host, which the server"
+	echo "  -p, --platform              Platform for which to try building the data "
+	echo "                              generation utility (one of ATT DOS HP IBM ICL MVS SGI"
+	echo "                              SUN U2200 VMS LINUX WIN32 MAC)"
+	echo "  -P, --port NUMBER           Network port on the local host, which the server"
 	echo "                              will related to the DB farm"
 	echo "  -D, --data-gen-dir PATH     directory in which to generate the TPC-H table data"
 	echo "  -k, --keep-raw-tables       Keep the raw data generated by the tool outside of"
 	echo "                              the DBMS"
 	echo "  -v, --verbose               Be verbose"
-	echo 
+	echo
 	echo "For more information, for feedback and for bug reports - please visit this tool's"
 	echo "source repository online at $REPOSITORY_URL ."
 }
 
 
 function die {
-	echo -e "$1" >&2   # error message to stderr 
+	echo -e "$1" >&2   # error message to stderr
 	exit ${2:-1}  # default exit code is -1 but you can specify something else
 }
 
@@ -102,26 +103,33 @@ function run_mclient {
     local queries="$1"
     local format="${2:-csv}"
     [[ $be_verbose ]] && echo "mclient -lsql -f $format -d $db_name -p $port -s \"\$queries\""
-    mclient -lsql -f $format -d $db_name -p $port -s "$queries" 
+    mclient -lsql -f $format -d $db_name -p $port -s "$queries"
 }
 
 function dbgen_is_valid {
 	[[ -n $($dbgen_binary -h 2>&1 | head -1 | grep "TPC-H Population Generator") ]]
 }
 
-
-function obtain_dbgen() {
-	VERSIONED_ARCHIVE_NAME="tpch_"$(echo $tpch_version | tr . _) 
-	mkdir -p "$dbgen_dir"
-	wget -q "http://www.tpc.org/tpch/spec/$VERSIONED_ARCHIVE_NAME.zip" || die "Failed obtaining the DB data generation utility from the TPC-H website."
-	unzip -d $dbgen_dir $VERSIONED_ARCHIVE_NAME.zip || die "Failed extraction TPC-H data generation utility archive." 
-	mv $dbgen_dir/$VERSIONED_ARCHIVE_NAME/dbgen/* $dbgen_dir || die "Failure setting up dbgen."
-	rm -r $dbgen_dir/$VERSIONED_ARCHIVE_NAME || die "Failure setting up dbgen."
-	rm $VERSIONED_ARCHIVE_NAME.zip
-	sed 's/^WORKLOAD = /WORKLOAD=TPCH/; s/^MACHINE = /MACHINE=LINUX/; s/DATABASE=/DATABASE=VECTORWISE/;' $dbgen_dir/makefile.suite > $DB_GEN/Makefile
-	make -C $dbgen_dir || die "Failed making the dbgen utility."
+function is_in_list {
+	local needle="$1"
+	shift
+	for haystack_item in $@; do
+		[[ "$needle" == "$haystack_item" ]] && found=1
+	done
+	[[ -n "$found" ]]
 }
 
+# This is a rather lame hack, but it seems to work for
+# Windows, Linux and MacOS. Note we're returning WIN32
+# even if it's 64-bit windows - for compatibility
+# with the TPC-H dbgen sources
+function get_platform {
+	if [ "$(uname)" == "Darwin" ]; then echo "MAC"
+	elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then echo "LINUX"
+	elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]; then echo "WIN32"
+	elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW64_NT" ]; then echo "WIN32"
+	fi
+}
 
 #------------------------------
 
@@ -129,13 +137,11 @@ TODAY=$(date +%Y-%m-%d)
 
 # Default parameter values here...
 
-tpch_version="2.17.1"
 scale_factor=1
 directory_of_script="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 dbgen_dir="${directory_of_script}/../dbgen"
 data_generation_base_dir="$PWD"
-data_generation_dir="${data_generation_base_dir}/tpch-dbgen-${TODAY}"
-#db_name=$(printf 'tpch-sf-%03d' $scale_factor)
+data_generation_dir="${data_generation_base_dir}/tpch_generated_tables_${TODAY}"
 log_file="${0}.log"
 keep_raw_tables=
 port=50000
@@ -153,9 +159,9 @@ while [[ $# > 0 ]]; do
 	-r|--recreate)
 	    recreate_db=1
 	    ;;
-	-t|--tpch-version|--tpch)
-		tpch_version="$2"
-		is_positive_int $scale_factor || die "Invalid scale factor $scale_factor"
+	-p|--platform|--machine|--os)
+		platform="$2"
+		is_in_list $platform ATT DOS HP IBM ICL MVS SGI SUN U2200 VMS LINUX WIN32 MAC || die "Invalid platform"
 		shift # past argument
 		;;
 	-s|--scale-factor|--sf)
@@ -164,10 +170,8 @@ while [[ $# > 0 ]]; do
 		shift # past argument
 		;;
 	-g|--dbgen-dir)
-		raw_db_dir="$2"
-		dbgen_dir=${raw_db_dir%%/}
-		dbgen_binary=$dbgen_dir/dbgen
-		dbgen_dists_file=$dbgen_dir/dists.dss
+		raw_dbgen_dir="$2"
+		dbgen_dir=${raw_dbgen_dir%%/}
 		shift # past argument
 		;;
 	-G|--data-already-generated|--already-generated|--have-generated-data|--have-generated)
@@ -185,7 +189,7 @@ while [[ $# > 0 ]]; do
 		db_farm="$2"
 		shift # past argument
 		;;
-	-p|--port|--dbfarm-port)
+	-P|--port|--dbfarm-port)
 		port="$2"
 		shift # past argument
 		is_positive_int $port || die "Invalid DB farm port $port"
@@ -201,8 +205,6 @@ while [[ $# > 0 ]]; do
 	*) # unknown option
 		echo "Unknown command line option $option_key" 1>&2
 		break
-#		usage
-#		exit -1
 		;;
 	esac
 	shift # past argument or value
@@ -215,6 +217,7 @@ fi
 [[ -n "$db_farm" ]] || db_farm="$DB_FARM"
 [[ -n "$db_farm" ]] || db_farm="$HOME/db_farms/monetdb"
 [[ -n "$db_name" ]] || db_name="tpch-sf-$scale_factor"
+[[ -n "$platform" ]] || platform="$(get_platform)"
 #
 #------------------------------
 
@@ -224,44 +227,43 @@ exec >& >(tee $log_file)
 # Derived non-user-controlled parameters
 
 if [[ -z "$already_generated" ]]; then
-		if [[ -z $dbgen_binary ]] || [[ -z $dbgen_dists_file ]] ; then
-			if [[ -z $dbgen_dir ]]; then
-				echo "Could not locate the TPC dbgen tool directory/binary & dists file" >&2
-				echo "(you did not specify their location using -g)"
-				echo "If you don't have them - they may be obtained from from http://www.tpc.org/tpch" >&2
-				exit -1
+	if [[ -z $dbgen_binary ]] || [[ -z $dbgen_dists_file ]] ; then
+		if [[ -z $dbgen_dir ]]; then
+			echo "Could not locate the TPC dbgen tool directory/binary & dists file" >&2
+			echo "(you did not specify their location using -g)"
+			echo "If you don't have them - they may be obtained from from http://www.tpc.org/tpch" >&2
+			exit -1
+		fi
+	fi
+	[[ -n $dbgen_dists_file ]] || dbgen_dists_file=$dbgen_dir/dists.dss
+	[[ -n $dbgen_binary ]] || dbgen_binary=$dbgen_dir/dbgen
+	if [[ ! -r $dbgen_dists_file ]]; then
+		echo "Cannot read dbgen dists file $dbgen_dists_file" >&2
+		exit -1
+	fi
+	if [[ ! -f $dbgen_binary ]]; then
+		[[ -n "$platform" ]] || die "Cannot determine the platform parameter necessary for building the TPC-H dbgen utility. You must specify it explicitly."
+		dbgen_binary="${dbgen_dir}/dbgen" # we'll build this...
+		if [[ ! -r $dbgen_dir/Makefile ]]; then
+			if [[ -r $dbgen_dir/CMakeLists.txt ]]; then
+				pushd $dbgen_dir
+				type cmake 1>/dev/null || die "CMake build tool unavailable"
+				cmake -DMachine=$platform -DDatabase=VECTORWISE . || die "Failure building the generation utility in $dbgen_dir - CMake failure"
+				popd
+			else
+				if [[ -f $dbgen_dir/makefile.suite ]]; then
+					sed 's/^WORKLOAD = /WORKLOAD=TPCH/; s/^MACHINE = /MACHINE='"$platform"'/; s/DATABASE=/DATABASE=VECTORWISE/;' $dbgen_dir/makefile.suite > $dbgen_dir/Makefile
+				fi
 			fi
-		#	dbgen_dir="$data_generation_dir"
-		#	obtain_dbgen
 		fi
-		[[ -n $dbgen_dists_file ]] || dbgen_dists_file=$dbgen_dir/dists.dss
-		[[ -n $dbgen_binary ]] || dbgen_binary=$dbgen_dir/dbgen
-		if [[ ! -r $dbgen_dists_file ]]; then
-			echo "Cannot read dbgen dists file $dbgen_dists_file" >&2
-			exit -1
-		fi
-		if [[ ! -f $dbgen_binary ]]; then
-			if [[ ! -f $dbgen_dir/Makefile ]]; then
-				[[ -f $dbgen_dir/makefile.suite ]] || die "Missing makefile.suit in the DBGEN directory $dbgen_dir"
-				# Sorry, we should really make an effort to determine which OS we're running under, rather than assuming
-				# it's Linux-like enough, but - I don't have to code that right now
-				sed 's/^WORKLOAD = /WORKLOAD=TPCH/; s/^MACHINE = /MACHINE=LINUX/; s/DATABASE=/DATABASE=VECTORWISE/;' $dbgen_dir/makefile.suite > $dbgen_dir/Makefile
-			fi
-			[[ -f $dbgen_dir/Makefile ]] || die "Could not find or generate a Makefile in $dbgen_dir"
-			make -C $dbgen_dir || die "Failed building the dbgen utility."
-		fi
-				
-		if [[ ! -f $dbgen_binary ]]; then
-			echo "Cannot find the dbgen data generation binary at $dbgen_binary. (Perhaps something went wrong with the build?)" >&2
-			exit -1
-		fi 
-		if [[ ! -x $dbgen_binary ]]; then
-			echo "The dbgen data generation binary at $dbgen_binary is not an executable file." >&2
-			exit -1
-		fi 
+		[[ -f $dbgen_dir/Makefile ]] || die "Could not find or generate a Makefile in $dbgen_dir for building the generator utility $dbgen_binary"
+		type make 1>/dev/null || die "GNU Make unavailable"
+		make -C $dbgen_dir || die "Failure building the generation utility in $dbgen_dir - Make failure"
+		[[ -f $dbgen_binary ]] || die "Although the build of $dbgen_binary has supposedly succeeded - the binary is missing."
+	fi
+	[[ -f $dbgen_binary ]] || die "Cannot find the dbgen data generation binary at $dbgen_binary"
+	[[ -x $dbgen_binary ]] || die "The generation utility $dbgen_binary is not an executable file."
 fi
-
-
 
 # Note: We don't really need that extra space, but... better be on the safe side (especially if the .tbl directory and the DB farm are on the same partition)
 necessary_space_in_gb=$(( 2 * $scale_factor ))
@@ -326,8 +328,8 @@ CREATE TABLE ORDERS  (  O_ORDERKEY       INTEGER NOT NULL,
                         O_ORDERSTATUS    CHAR(1) NOT NULL,
                         O_TOTALPRICE     DECIMAL(15,2) NOT NULL,
                         O_ORDERDATE      DATE NOT NULL,
-                        O_ORDERPRIORITY  CHAR(15) NOT NULL,  
-                        O_CLERK          CHAR(15) NOT NULL, 
+                        O_ORDERPRIORITY  CHAR(15) NOT NULL,
+                        O_CLERK          CHAR(15) NOT NULL,
                         O_SHIPPRIORITY   INTEGER NOT NULL,
                         O_COMMENT        VARCHAR(79) NOT NULL,
                         PRIMARY KEY      (O_ORDERKEY),
@@ -390,7 +392,7 @@ done
 
 if [[ -z "$already_generated" ]]; then
 	[[ ! -d $data_generation_dir ]] || die "The intended data generation directory $data_generation_dir is already present;\nYou must either remove it, name a subdir, or set -G if it contains the generated data"
-	(( $(gb_available_space_for_dir $data_generation_base_dir) > $necessary_space_in_gb )) || 
+	(( $(gb_available_space_for_dir $data_generation_base_dir) > $necessary_space_in_gb )) ||
 	die "Not enough disk space at $data_generation_base_dir to generate the TPC-H data: We need ${NECCESSARY_SPACE_IN_GB} GiB but have $(gb_available_space_for_dir $data_generation_base_dir) GiB."
 fi
 
@@ -403,7 +405,7 @@ if db_farm_exists $db_farm; then
     port=$(property_of_dbfarm "port" $db_farm)
     db_farm_is_up $db_farm || monetdbd start $db_farm || die "Could not start the DB farm at $db_farm"
 else
-    [[ "$be_verbose" ]] && echo "monetdbd create $db_farm" 
+    [[ "$be_verbose" ]] && echo "monetdbd create $db_farm"
     monetdbd create $db_farm || die "A MonetDB database farm does not exist at ${db_farm}, and cannot be created there."
     [[ "$be_verbose" ]] && echo "monetdbd set port=$port $db_farm"
     monetdbd set port=$port $db_farm || die "Can't set the daemon port for new DB farm ${db_farm} to ${port}."
@@ -419,7 +421,7 @@ if db_exists "$db_name" "$port"; then
         monetdb -p $port stop $db_name  >/dev/null || die "Can't stop the existing DB named $db_name in DB farm $db_farm."
     fi
     if [[ "$recreate_db" ]]; then
-        [[ "$be_verbose" ]] &&  echo "monetdb -p $port destroy -f $db_name" 
+        [[ "$be_verbose" ]] &&  echo "monetdb -p $port destroy -f $db_name"
         monetdb -p $port destroy -f $db_name >/dev/null || die "Failed destroying the existing DB named $db_name in DB farm $db_farm."
         need_to_create_the_db=1
     else
@@ -432,7 +434,7 @@ fi
 (( $(gb_available_space_for_dir $db_farm) > $necessary_space_in_gb )) ||
 die "Not enough disk space at $db_farm to generate the TPC-H data: We need ${necessary_space_in_gb} GiB but have $(gb_available_space_for_dir $db_farm) GiB."
 
-# Create the DB and SQL-create its schema 
+# Create the DB and SQL-create its schema
 
 if [[ "$need_to_create_the_db" ]]; then
 	[[ "$be_verbose" ]] && echo "Creating the empty database $db_name in DB farm $db_farm"
@@ -460,7 +462,6 @@ else
 fi
 
 # Data generation is complete, time to load it
- 
 [[ "$be_verbose" ]] && echo "Loading generated data from $data_generation_dir"
 for table_name in region nation supplier customer part partsupp orders lineitem; do
 	table_file="$data_generation_dir/${table_name}.tbl"
